### PR TITLE
Update @embroider/macros to v1.0.0

### PR DESCRIPTION
**Pull request by navels**
Context: https://github.com/embroider-build/embroider/issues/1077

### CODE REVIEW

**Comment by navels** [comment]
Now that @embroider/macros v1 is out, switching to that.

**Comment by SergeAstapov** [comment]
@mansona would you mind to release this as patch version?

**Comment by SergeAstapov** [comment]
@navels could you please rebase to resolve conflicts?

**Comment by navels** [comment]
Done!

**Comment by SergeAstapov** [comment]
@navels could you please move `ember-cli-htmlbars` back to `devDependencies`? otherwise it will cancel #33.

@navels also, could you please bump `@embroider/test-setup` to `^1.0.0` as well as `ember-auto-import: ^2.3.0`? I suspect CI would fail without these additional changes (which would sync `@embroider/*` packages in the deps tree).

**Comment by navels** [comment]
Updated, thanks!

**Review by SergeAstapov — APPROVED** [review]

**Comment by mansona** [comment]
@SergeAstapov I made a change to the dependency declaration, I wasn't comfortable bumping the dependency and doing it as a patch

and since v1 is essentially v0.50 anyway I thought being more lenient for the dependencies was a good idea 👍

**Pull request merged**
